### ISSUE TITLE
Name change breakage

### ISSUE THREAD

**Issue by lowell** [NerdNu/CHClanChat#10]
https://mojang.com/2015/01/announcing-minecraft-name-changes/

Mojang enabled name changes a few minutes ago and clan chat is treating my account like that of a new player. I don't have perms in any of my channels anyway, but others who do might run into problems if they update their player names.

**Comment by slide23** [comment]
Thanks, we are aware and are working hard to upgrade everything. Your previous clanchats will work again either tonight or tomorrow.

**Comment by lowell** [comment]
\o/

You all are awesome! As usual.

**Comment by slide23** [comment]
Should be fixed with commit 882b629b8318e93423123b59a5d1da505b16cb71 data may need some additional cleanup, let me know if your channels are back.

**Comment by lowell** [comment]
Yup, they are! Thanks so much!
